font_family FiraCode Nerd Font Mono
font_size 14

confirm_os_window_close 0
cursor_shape beam
enable_audio_bell no

background_opacity 0.9
# background_opacity 1
dynamic_background_opacity yes

bold_font auto
italic_font auto
bold_italic_font auto

allow_remote_control no
listen_on unix:/tmp/mykitty

copy_on_select clipboard
strip_trailing_spaces smart

include ~/.cache/wallust/kitty.conf

map ctrl+backspace send_text all \x17

underline_hyperlinks always
detect_urls yes

open_url_with default

scrollback_lines 2000
wheel_scroll_min_lines 1
text_composition_strategy legacy

# Undercurl
undercurl_style thin-dense
# url_style curly
show_hyperlink_targets yes

window_padding_width 15 15

allow_hyperlinks yes
resize_debounce_time 0.1
cursor_blink_interval 0

# selection_foreground none
# selection_background none