# -------------------------
# MONITORS
# -------------------------

monitor=,preferred,auto,1

# -------------------------
# Sourcing Files
# -------------------------
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/decoration.conf
source = ~/.config/hypr/modules/animations.conf
source = ~/.config/hypr/modules/windowrules.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/bind.conf

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}