# -------------------------
# ANIMATIONS
# -------------------------

animations {
    enabled = yes

    bezier = smooth, 0.25, 0.1, 0.25, 1.0

    animation = windows, 1, 6, smooth
    animation = windowsIn, 1, 6, smooth
    animation = windowsOut, 1, 5, smooth, popin 85%

    animation = fade, 1, 5, smooth

    animation = border, 1, 8, default

    animation = workspaces, 1, 5, smooth
}

