# -------------------------
# AUTOSTART
# -------------------------

exec-once = waybar
exec-once = swaync

# exec-once = ~/.config/waybar/scripts/launch.sh

exec-once = swww-daemon

exec-once = kitty --listen-on unix:/tmp/mykitty