# -------------------------
# INPUT
# -------------------------

input {
    kb_layout = us

    touchpad {
        # do false to invert scroll
        natural_scroll = true
        # tap-to-click = true
        # drag_lock = true
    }

    follow_mouse = 1
    sensitivity = 0

    # scroll speed
    scroll_factor = 0.4
}

gesture = 4, horizontal, workspace